2024-03-18 20:17:08,407:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2024-03-18 20:17:08,407:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2024-03-18 20:17:08,407:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2024-03-18 20:17:08,407:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2024-03-18 20:17:09,989:INFO:PyCaret ClassificationExperiment
2024-03-18 20:17:09,990:INFO:Logging name: clf-default-name
2024-03-18 20:17:09,992:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2024-03-18 20:17:09,992:INFO:version 3.3.0
2024-03-18 20:17:09,992:INFO:Initializing setup()
2024-03-18 20:17:09,992:INFO:self.USI: 77af
2024-03-18 20:17:09,992:INFO:self._variable_keys: {'fold_groups_param', 'gpu_param', 'is_multiclass', 'gpu_n_jobs_param', 'n_jobs_param', '_ml_usecase', 'y_train', 'fold_shuffle_param', 'html_param', 'log_plots_param', 'logging_param', '_available_plots', 'seed', 'pipeline', 'y_test', 'memory', 'y', 'X', 'USI', 'exp_name_log', 'exp_id', 'X_test', 'data', 'target_param', 'idx', 'X_train', 'fold_generator', 'fix_imbalance'}
2024-03-18 20:17:09,992:INFO:Checking environment
2024-03-18 20:17:09,992:INFO:python_version: 3.10.9
2024-03-18 20:17:09,992:INFO:python_build: ('main', 'Feb  2 2023 20:14:58')
2024-03-18 20:17:09,992:INFO:machine: AMD64
2024-03-18 20:17:09,992:INFO:platform: Windows-10-10.0.19045-SP0
2024-03-18 20:17:09,992:INFO:Memory: svmem(total=7916032000, available=963747840, percent=87.8, used=6952284160, free=963747840)
2024-03-18 20:17:09,993:INFO:Physical Core: 6
2024-03-18 20:17:09,993:INFO:Logical Core: 12
2024-03-18 20:17:09,993:INFO:Checking libraries
2024-03-18 20:17:09,993:INFO:System:
2024-03-18 20:17:09,993:INFO:    python: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:14:58) [MSC v.1929 64 bit (AMD64)]
2024-03-18 20:17:09,993:INFO:executable: c:\Users\YK\anaconda3\envs\pyt\python.exe
2024-03-18 20:17:09,993:INFO:   machine: Windows-10-10.0.19045-SP0
2024-03-18 20:17:09,993:INFO:PyCaret required dependencies:
2024-03-18 20:17:09,999:INFO:                 pip: 24.0
2024-03-18 20:17:09,999:INFO:          setuptools: 68.0.0
2024-03-18 20:17:09,999:INFO:             pycaret: 3.3.0
2024-03-18 20:17:09,999:INFO:             IPython: 8.18.1
2024-03-18 20:17:09,999:INFO:          ipywidgets: 7.8.1
2024-03-18 20:17:10,000:INFO:                tqdm: 4.65.0
2024-03-18 20:17:10,000:INFO:               numpy: 1.23.5
2024-03-18 20:17:10,000:INFO:              pandas: 1.5.3
2024-03-18 20:17:10,000:INFO:              jinja2: 3.0.3
2024-03-18 20:17:10,000:INFO:               scipy: 1.10.1
2024-03-18 20:17:10,000:INFO:              joblib: 1.2.0
2024-03-18 20:17:10,000:INFO:             sklearn: 1.4.1.post1
2024-03-18 20:17:10,000:INFO:                pyod: 1.1.3
2024-03-18 20:17:10,000:INFO:            imblearn: 0.12.0
2024-03-18 20:17:10,000:INFO:   category_encoders: 2.6.0
2024-03-18 20:17:10,000:INFO:            lightgbm: 3.3.5
2024-03-18 20:17:10,000:INFO:               numba: 0.56.4
2024-03-18 20:17:10,000:INFO:            requests: 2.27.1
2024-03-18 20:17:10,000:INFO:          matplotlib: 3.7.0
2024-03-18 20:17:10,001:INFO:          scikitplot: 0.3.7
2024-03-18 20:17:10,001:INFO:         yellowbrick: 1.5
2024-03-18 20:17:10,001:INFO:              plotly: 5.20.0
2024-03-18 20:17:10,001:INFO:    plotly-resampler: Not installed
2024-03-18 20:17:10,001:INFO:             kaleido: 0.2.1
2024-03-18 20:17:10,001:INFO:           schemdraw: 0.15
2024-03-18 20:17:10,001:INFO:         statsmodels: 0.13.5
2024-03-18 20:17:10,001:INFO:              sktime: 0.27.0
2024-03-18 20:17:10,001:INFO:               tbats: 1.1.3
2024-03-18 20:17:10,001:INFO:            pmdarima: 2.0.4
2024-03-18 20:17:10,001:INFO:              psutil: 5.9.0
2024-03-18 20:17:10,001:INFO:          markupsafe: 2.0.1
2024-03-18 20:17:10,001:INFO:             pickle5: Not installed
2024-03-18 20:17:10,002:INFO:         cloudpickle: 2.2.1
2024-03-18 20:17:10,002:INFO:         deprecation: 2.1.0
2024-03-18 20:17:10,002:INFO:              xxhash: 3.2.0
2024-03-18 20:17:10,002:INFO:           wurlitzer: Not installed
2024-03-18 20:17:10,002:INFO:PyCaret optional dependencies:
2024-03-18 20:17:11,026:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\huggingface_hub\utils\_runtime.py:184: UserWarning: Pydantic is installed but cannot be imported. Please check your installation. `huggingface_hub` will default to not using Pydantic. Error message: '{e}'
  warnings.warn(

2024-03-18 20:17:11,629:INFO:                shap: 0.41.0
2024-03-18 20:17:11,629:INFO:           interpret: Not installed
2024-03-18 20:17:11,629:INFO:                umap: 0.5.5
2024-03-18 20:17:11,629:INFO:     ydata_profiling: Not installed
2024-03-18 20:17:11,630:INFO:  explainerdashboard: Not installed
2024-03-18 20:17:11,630:INFO:             autoviz: Not installed
2024-03-18 20:17:11,630:INFO:           fairlearn: Not installed
2024-03-18 20:17:11,630:INFO:          deepchecks: Not installed
2024-03-18 20:17:11,630:INFO:             xgboost: 1.6.2
2024-03-18 20:17:11,630:INFO:            catboost: 1.1.1
2024-03-18 20:17:11,630:INFO:              kmodes: Not installed
2024-03-18 20:17:11,630:INFO:             mlxtend: Not installed
2024-03-18 20:17:11,630:INFO:       statsforecast: 1.6.0
2024-03-18 20:17:11,630:INFO:        tune_sklearn: Not installed
2024-03-18 20:17:11,630:INFO:                 ray: Not installed
2024-03-18 20:17:11,630:INFO:            hyperopt: 0.2.7
2024-03-18 20:17:11,630:INFO:              optuna: Not installed
2024-03-18 20:17:11,630:INFO:               skopt: Not installed
2024-03-18 20:17:11,631:INFO:              mlflow: Not installed
2024-03-18 20:17:11,631:INFO:              gradio: Not installed
2024-03-18 20:17:11,631:INFO:             fastapi: Not installed
2024-03-18 20:17:11,631:INFO:             uvicorn: 0.27.0
2024-03-18 20:17:11,631:INFO:              m2cgen: Not installed
2024-03-18 20:17:11,631:INFO:           evidently: Not installed
2024-03-18 20:17:11,631:INFO:               fugue: 0.8.7
2024-03-18 20:17:11,631:INFO:           streamlit: 1.20.0
2024-03-18 20:17:11,631:INFO:             prophet: 1.1.2
2024-03-18 20:17:11,631:INFO:None
2024-03-18 20:17:11,631:INFO:Set up data.
2024-03-18 20:17:11,644:INFO:Set up folding strategy.
2024-03-18 20:17:11,645:INFO:Set up train/test split.
2024-03-18 20:17:11,655:INFO:Set up index.
2024-03-18 20:17:11,656:INFO:Assigning column types.
2024-03-18 20:17:11,662:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2024-03-18 20:17:11,749:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2024-03-18 20:17:11,756:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2024-03-18 20:17:11,826:INFO:Soft dependency imported: xgboost: 1.6.2
2024-03-18 20:17:12,876:INFO:Soft dependency imported: catboost: 1.1.1
2024-03-18 20:17:12,967:WARNING:<frozen importlib._bootstrap>:241: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 232 from PyObject

2024-03-18 20:17:13,095:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2024-03-18 20:17:13,097:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2024-03-18 20:17:13,153:INFO:Soft dependency imported: xgboost: 1.6.2
2024-03-18 20:17:13,160:INFO:Soft dependency imported: catboost: 1.1.1
2024-03-18 20:17:13,161:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2024-03-18 20:17:13,274:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2024-03-18 20:17:13,338:INFO:Soft dependency imported: xgboost: 1.6.2
2024-03-18 20:17:13,343:INFO:Soft dependency imported: catboost: 1.1.1
2024-03-18 20:17:13,433:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2024-03-18 20:17:13,486:INFO:Soft dependency imported: xgboost: 1.6.2
2024-03-18 20:17:13,491:INFO:Soft dependency imported: catboost: 1.1.1
2024-03-18 20:17:13,492:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2024-03-18 20:17:13,635:INFO:Soft dependency imported: xgboost: 1.6.2
2024-03-18 20:17:13,641:INFO:Soft dependency imported: catboost: 1.1.1
2024-03-18 20:17:13,787:INFO:Soft dependency imported: xgboost: 1.6.2
2024-03-18 20:17:13,792:INFO:Soft dependency imported: catboost: 1.1.1
2024-03-18 20:17:13,796:INFO:Preparing preprocessing pipeline...
2024-03-18 20:17:13,839:INFO:Set up simple imputation.
2024-03-18 20:17:13,914:INFO:Finished creating preprocessing pipeline.
2024-03-18 20:17:13,928:INFO:Pipeline: Pipeline(memory=FastMemory(location=C:\Users\YK\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['Bp', 'Sg', 'Al', 'Su', 'Rbc',
                                             'Bu', 'Sc', 'Sod', 'Pot', 'Hemo',
                                             'Wbcc', 'Rbcc', 'Htn'],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='mean'))),
                ('categorical_imputer',
                 TransformerWrapper(exclude=None, include=[],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='most_frequent')))],
         verbose=False)
2024-03-18 20:17:13,928:INFO:Creating final display dataframe.
2024-03-18 20:17:14,056:INFO:Setup _display_container:                     Description             Value
0                    Session id              7931
1                        Target             Class
2                   Target type            Binary
3           Original data shape         (400, 14)
4        Transformed data shape         (400, 14)
5   Transformed train set shape         (280, 14)
6    Transformed test set shape         (120, 14)
7              Numeric features                13
8                    Preprocess              True
9               Imputation type            simple
10           Numeric imputation              mean
11       Categorical imputation              mode
12               Fold Generator   StratifiedKFold
13                  Fold Number                10
14                     CPU Jobs                -1
15                      Use GPU             False
16               Log Experiment             False
17              Experiment Name  clf-default-name
18                          USI              77af
2024-03-18 20:17:14,232:INFO:Soft dependency imported: xgboost: 1.6.2
2024-03-18 20:17:14,237:INFO:Soft dependency imported: catboost: 1.1.1
2024-03-18 20:17:14,394:INFO:Soft dependency imported: xgboost: 1.6.2
2024-03-18 20:17:14,400:INFO:Soft dependency imported: catboost: 1.1.1
2024-03-18 20:17:14,442:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py:51: FutureWarning: The `needs_threshold` and `needs_proba` parameter are deprecated in version 1.4 and will be removed in 1.6. You can either let `response_method` be `None` or set it to `predict` to preserve the same behaviour.
  warnings.warn(

2024-03-18 20:17:14,445:INFO:setup() successfully completed in 4.51s...............
2024-03-18 20:17:14,446:INFO:Initializing compare_models()
2024-03-18 20:17:14,446:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000017B2EE0B8E0>, include=None, fold=None, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x0000017B2EE0B8E0>, 'include': None, 'exclude': None, 'fold': None, 'round': 4, 'cross_validation': True, 'sort': 'Accuracy', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>}, exclude=None)
2024-03-18 20:17:14,446:INFO:Checking exceptions
2024-03-18 20:17:14,452:INFO:Preparing display monitor
2024-03-18 20:17:14,526:INFO:Initializing Logistic Regression
2024-03-18 20:17:14,527:INFO:Total runtime is 0.0 minutes
2024-03-18 20:17:14,536:INFO:SubProcess create_model() called ==================================
2024-03-18 20:17:14,537:INFO:Initializing create_model()
2024-03-18 20:17:14,537:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000017B2EE0B8E0>, estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000017B4DA55000>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-03-18 20:17:14,538:INFO:Checking exceptions
2024-03-18 20:17:14,538:INFO:Importing libraries
2024-03-18 20:17:14,538:INFO:Copying training dataset
2024-03-18 20:17:14,548:INFO:Defining folds
2024-03-18 20:17:14,548:INFO:Declaring metric variables
2024-03-18 20:17:14,559:INFO:Importing untrained model
2024-03-18 20:17:14,569:INFO:Logistic Regression Imported successfully
2024-03-18 20:17:14,600:INFO:Starting cross validation
2024-03-18 20:17:14,602:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2024-03-18 20:17:24,534:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2024-03-18 20:17:24,537:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2024-03-18 20:17:24,538:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2024-03-18 20:17:24,541:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2024-03-18 20:17:24,542:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2024-03-18 20:17:24,543:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2024-03-18 20:17:24,549:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2024-03-18 20:17:24,550:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2024-03-18 20:17:24,561:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2024-03-18 20:17:24,574:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2024-03-18 20:17:24,635:INFO:Calculating mean and std
2024-03-18 20:17:24,638:INFO:Creating metrics dataframe
2024-03-18 20:17:24,650:INFO:Uploading results into container
2024-03-18 20:17:24,652:INFO:Uploading model into container now
2024-03-18 20:17:24,654:INFO:_master_model_container: 1
2024-03-18 20:17:24,655:INFO:_display_container: 2
2024-03-18 20:17:24,656:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=7931, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2024-03-18 20:17:24,657:INFO:create_model() successfully completed......................................
2024-03-18 20:17:24,876:INFO:SubProcess create_model() end ==================================
2024-03-18 20:17:24,876:INFO:Creating metrics dataframe
2024-03-18 20:17:24,889:INFO:Initializing K Neighbors Classifier
2024-03-18 20:17:24,890:INFO:Total runtime is 0.17272035280863443 minutes
2024-03-18 20:17:24,894:INFO:SubProcess create_model() called ==================================
2024-03-18 20:17:24,895:INFO:Initializing create_model()
2024-03-18 20:17:24,895:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000017B2EE0B8E0>, estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000017B4DA55000>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-03-18 20:17:24,895:INFO:Checking exceptions
2024-03-18 20:17:24,896:INFO:Importing libraries
2024-03-18 20:17:24,896:INFO:Copying training dataset
2024-03-18 20:17:24,903:INFO:Defining folds
2024-03-18 20:17:24,903:INFO:Declaring metric variables
2024-03-18 20:17:24,909:INFO:Importing untrained model
2024-03-18 20:17:24,915:INFO:K Neighbors Classifier Imported successfully
2024-03-18 20:17:24,927:INFO:Starting cross validation
2024-03-18 20:17:24,928:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2024-03-18 20:17:29,840:INFO:Calculating mean and std
2024-03-18 20:17:29,841:INFO:Creating metrics dataframe
2024-03-18 20:17:29,847:INFO:Uploading results into container
2024-03-18 20:17:29,849:INFO:Uploading model into container now
2024-03-18 20:17:29,849:INFO:_master_model_container: 2
2024-03-18 20:17:29,849:INFO:_display_container: 2
2024-03-18 20:17:29,850:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2024-03-18 20:17:29,850:INFO:create_model() successfully completed......................................
2024-03-18 20:17:29,970:INFO:SubProcess create_model() end ==================================
2024-03-18 20:17:29,970:INFO:Creating metrics dataframe
2024-03-18 20:17:30,025:INFO:Initializing Naive Bayes
2024-03-18 20:17:30,025:INFO:Total runtime is 0.25830414295196535 minutes
2024-03-18 20:17:30,032:INFO:SubProcess create_model() called ==================================
2024-03-18 20:17:30,032:INFO:Initializing create_model()
2024-03-18 20:17:30,032:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000017B2EE0B8E0>, estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000017B4DA55000>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-03-18 20:17:30,032:INFO:Checking exceptions
2024-03-18 20:17:30,033:INFO:Importing libraries
2024-03-18 20:17:30,033:INFO:Copying training dataset
2024-03-18 20:17:30,041:INFO:Defining folds
2024-03-18 20:17:30,041:INFO:Declaring metric variables
2024-03-18 20:17:30,061:INFO:Importing untrained model
2024-03-18 20:17:30,071:INFO:Naive Bayes Imported successfully
2024-03-18 20:17:30,089:INFO:Starting cross validation
2024-03-18 20:17:30,091:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2024-03-18 20:17:30,201:INFO:Calculating mean and std
2024-03-18 20:17:30,203:INFO:Creating metrics dataframe
2024-03-18 20:17:30,207:INFO:Uploading results into container
2024-03-18 20:17:30,208:INFO:Uploading model into container now
2024-03-18 20:17:30,208:INFO:_master_model_container: 3
2024-03-18 20:17:30,208:INFO:_display_container: 2
2024-03-18 20:17:30,209:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2024-03-18 20:17:30,209:INFO:create_model() successfully completed......................................
2024-03-18 20:17:30,324:INFO:SubProcess create_model() end ==================================
2024-03-18 20:17:30,324:INFO:Creating metrics dataframe
2024-03-18 20:17:30,336:INFO:Initializing Decision Tree Classifier
2024-03-18 20:17:30,337:INFO:Total runtime is 0.26351750691731773 minutes
2024-03-18 20:17:30,341:INFO:SubProcess create_model() called ==================================
2024-03-18 20:17:30,341:INFO:Initializing create_model()
2024-03-18 20:17:30,342:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000017B2EE0B8E0>, estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000017B4DA55000>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-03-18 20:17:30,342:INFO:Checking exceptions
2024-03-18 20:17:30,342:INFO:Importing libraries
2024-03-18 20:17:30,342:INFO:Copying training dataset
2024-03-18 20:17:30,347:INFO:Defining folds
2024-03-18 20:17:30,348:INFO:Declaring metric variables
2024-03-18 20:17:30,352:INFO:Importing untrained model
2024-03-18 20:17:30,358:INFO:Decision Tree Classifier Imported successfully
2024-03-18 20:17:30,368:INFO:Starting cross validation
2024-03-18 20:17:30,371:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2024-03-18 20:17:30,508:INFO:Calculating mean and std
2024-03-18 20:17:30,509:INFO:Creating metrics dataframe
2024-03-18 20:17:30,513:INFO:Uploading results into container
2024-03-18 20:17:30,514:INFO:Uploading model into container now
2024-03-18 20:17:30,514:INFO:_master_model_container: 4
2024-03-18 20:17:30,514:INFO:_display_container: 2
2024-03-18 20:17:30,515:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       monotonic_cst=None, random_state=7931, splitter='best')
2024-03-18 20:17:30,515:INFO:create_model() successfully completed......................................
2024-03-18 20:17:30,623:INFO:SubProcess create_model() end ==================================
2024-03-18 20:17:30,623:INFO:Creating metrics dataframe
2024-03-18 20:17:30,635:INFO:Initializing SVM - Linear Kernel
2024-03-18 20:17:30,635:INFO:Total runtime is 0.2684757669766744 minutes
2024-03-18 20:17:30,640:INFO:SubProcess create_model() called ==================================
2024-03-18 20:17:30,640:INFO:Initializing create_model()
2024-03-18 20:17:30,640:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000017B2EE0B8E0>, estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000017B4DA55000>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-03-18 20:17:30,640:INFO:Checking exceptions
2024-03-18 20:17:30,640:INFO:Importing libraries
2024-03-18 20:17:30,640:INFO:Copying training dataset
2024-03-18 20:17:30,645:INFO:Defining folds
2024-03-18 20:17:30,645:INFO:Declaring metric variables
2024-03-18 20:17:30,651:INFO:Importing untrained model
2024-03-18 20:17:30,656:INFO:SVM - Linear Kernel Imported successfully
2024-03-18 20:17:30,665:INFO:Starting cross validation
2024-03-18 20:17:30,667:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2024-03-18 20:17:30,759:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py:196: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method='predict_proba', average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 188, in _score
    return super()._score(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_scorer.py", line 344, in _score
    response_method = _check_response_method(estimator, self._response_method)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 2106, in _check_response_method
    raise AttributeError(
AttributeError: Pipeline has none of the following attributes: predict_proba.

  warnings.warn(

2024-03-18 20:17:30,760:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py:196: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method='predict_proba', average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 188, in _score
    return super()._score(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_scorer.py", line 344, in _score
    response_method = _check_response_method(estimator, self._response_method)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 2106, in _check_response_method
    raise AttributeError(
AttributeError: Pipeline has none of the following attributes: predict_proba.

  warnings.warn(

2024-03-18 20:17:30,761:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py:196: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method='predict_proba', average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 188, in _score
    return super()._score(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_scorer.py", line 344, in _score
    response_method = _check_response_method(estimator, self._response_method)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 2106, in _check_response_method
    raise AttributeError(
AttributeError: Pipeline has none of the following attributes: predict_proba.

  warnings.warn(

2024-03-18 20:17:30,762:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py:196: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method='predict_proba', average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 188, in _score
    return super()._score(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_scorer.py", line 344, in _score
    response_method = _check_response_method(estimator, self._response_method)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 2106, in _check_response_method
    raise AttributeError(
AttributeError: Pipeline has none of the following attributes: predict_proba.

  warnings.warn(

2024-03-18 20:17:30,766:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py:196: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method='predict_proba', average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 188, in _score
    return super()._score(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_scorer.py", line 344, in _score
    response_method = _check_response_method(estimator, self._response_method)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 2106, in _check_response_method
    raise AttributeError(
AttributeError: Pipeline has none of the following attributes: predict_proba.

  warnings.warn(

2024-03-18 20:17:30,770:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py:196: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method='predict_proba', average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 188, in _score
    return super()._score(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_scorer.py", line 344, in _score
    response_method = _check_response_method(estimator, self._response_method)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 2106, in _check_response_method
    raise AttributeError(
AttributeError: Pipeline has none of the following attributes: predict_proba.

  warnings.warn(

2024-03-18 20:17:30,771:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py:196: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method='predict_proba', average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 188, in _score
    return super()._score(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_scorer.py", line 344, in _score
    response_method = _check_response_method(estimator, self._response_method)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 2106, in _check_response_method
    raise AttributeError(
AttributeError: Pipeline has none of the following attributes: predict_proba.

  warnings.warn(

2024-03-18 20:17:30,776:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2024-03-18 20:17:30,777:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py:196: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method='predict_proba', average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 188, in _score
    return super()._score(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_scorer.py", line 344, in _score
    response_method = _check_response_method(estimator, self._response_method)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 2106, in _check_response_method
    raise AttributeError(
AttributeError: Pipeline has none of the following attributes: predict_proba.

  warnings.warn(

2024-03-18 20:17:30,777:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py:196: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method='predict_proba', average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 188, in _score
    return super()._score(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_scorer.py", line 344, in _score
    response_method = _check_response_method(estimator, self._response_method)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 2106, in _check_response_method
    raise AttributeError(
AttributeError: Pipeline has none of the following attributes: predict_proba.

  warnings.warn(

2024-03-18 20:17:30,788:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py:196: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method='predict_proba', average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 188, in _score
    return super()._score(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_scorer.py", line 344, in _score
    response_method = _check_response_method(estimator, self._response_method)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 2106, in _check_response_method
    raise AttributeError(
AttributeError: Pipeline has none of the following attributes: predict_proba.

  warnings.warn(

2024-03-18 20:17:30,789:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2024-03-18 20:17:30,813:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2024-03-18 20:17:30,823:INFO:Calculating mean and std
2024-03-18 20:17:30,825:INFO:Creating metrics dataframe
2024-03-18 20:17:30,831:INFO:Uploading results into container
2024-03-18 20:17:30,832:INFO:Uploading model into container now
2024-03-18 20:17:30,833:INFO:_master_model_container: 5
2024-03-18 20:17:30,833:INFO:_display_container: 2
2024-03-18 20:17:30,835:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=7931, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2024-03-18 20:17:30,835:INFO:create_model() successfully completed......................................
2024-03-18 20:17:30,949:INFO:SubProcess create_model() end ==================================
2024-03-18 20:17:30,949:INFO:Creating metrics dataframe
2024-03-18 20:17:30,962:INFO:Initializing Ridge Classifier
2024-03-18 20:17:30,963:INFO:Total runtime is 0.27394316196441654 minutes
2024-03-18 20:17:30,968:INFO:SubProcess create_model() called ==================================
2024-03-18 20:17:30,968:INFO:Initializing create_model()
2024-03-18 20:17:30,968:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000017B2EE0B8E0>, estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000017B4DA55000>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-03-18 20:17:30,968:INFO:Checking exceptions
2024-03-18 20:17:30,968:INFO:Importing libraries
2024-03-18 20:17:30,968:INFO:Copying training dataset
2024-03-18 20:17:30,972:INFO:Defining folds
2024-03-18 20:17:30,973:INFO:Declaring metric variables
2024-03-18 20:17:30,977:INFO:Importing untrained model
2024-03-18 20:17:30,983:INFO:Ridge Classifier Imported successfully
2024-03-18 20:17:30,992:INFO:Starting cross validation
2024-03-18 20:17:30,993:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2024-03-18 20:17:31,074:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\linear_model\_ridge.py:204: LinAlgWarning: Ill-conditioned matrix (rcond=6.65285e-10): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2024-03-18 20:17:31,074:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\linear_model\_ridge.py:204: LinAlgWarning: Ill-conditioned matrix (rcond=5.8268e-10): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2024-03-18 20:17:31,074:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\linear_model\_ridge.py:204: LinAlgWarning: Ill-conditioned matrix (rcond=5.64928e-10): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2024-03-18 20:17:31,075:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\linear_model\_ridge.py:204: LinAlgWarning: Ill-conditioned matrix (rcond=6.24326e-10): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2024-03-18 20:17:31,075:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\linear_model\_ridge.py:204: LinAlgWarning: Ill-conditioned matrix (rcond=5.7851e-10): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2024-03-18 20:17:31,076:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\linear_model\_ridge.py:204: LinAlgWarning: Ill-conditioned matrix (rcond=6.78223e-10): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2024-03-18 20:17:31,076:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\linear_model\_ridge.py:204: LinAlgWarning: Ill-conditioned matrix (rcond=5.66335e-10): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2024-03-18 20:17:31,077:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\linear_model\_ridge.py:204: LinAlgWarning: Ill-conditioned matrix (rcond=5.77265e-10): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2024-03-18 20:17:31,086:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py:196: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method='predict_proba', average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 188, in _score
    return super()._score(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_scorer.py", line 344, in _score
    response_method = _check_response_method(estimator, self._response_method)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 2106, in _check_response_method
    raise AttributeError(
AttributeError: Pipeline has none of the following attributes: predict_proba.

  warnings.warn(

2024-03-18 20:17:31,086:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py:196: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method='predict_proba', average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 188, in _score
    return super()._score(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_scorer.py", line 344, in _score
    response_method = _check_response_method(estimator, self._response_method)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 2106, in _check_response_method
    raise AttributeError(
AttributeError: Pipeline has none of the following attributes: predict_proba.

  warnings.warn(

2024-03-18 20:17:31,089:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py:196: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method='predict_proba', average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 188, in _score
    return super()._score(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_scorer.py", line 344, in _score
    response_method = _check_response_method(estimator, self._response_method)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 2106, in _check_response_method
    raise AttributeError(
AttributeError: Pipeline has none of the following attributes: predict_proba.

  warnings.warn(

2024-03-18 20:17:31,090:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py:196: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method='predict_proba', average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 188, in _score
    return super()._score(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_scorer.py", line 344, in _score
    response_method = _check_response_method(estimator, self._response_method)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 2106, in _check_response_method
    raise AttributeError(
AttributeError: Pipeline has none of the following attributes: predict_proba.

  warnings.warn(

2024-03-18 20:17:31,090:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py:196: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method='predict_proba', average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 188, in _score
    return super()._score(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_scorer.py", line 344, in _score
    response_method = _check_response_method(estimator, self._response_method)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 2106, in _check_response_method
    raise AttributeError(
AttributeError: Pipeline has none of the following attributes: predict_proba.

  warnings.warn(

2024-03-18 20:17:31,091:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py:196: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method='predict_proba', average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 188, in _score
    return super()._score(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_scorer.py", line 344, in _score
    response_method = _check_response_method(estimator, self._response_method)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 2106, in _check_response_method
    raise AttributeError(
AttributeError: Pipeline has none of the following attributes: predict_proba.

  warnings.warn(

2024-03-18 20:17:31,091:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py:196: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method='predict_proba', average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 188, in _score
    return super()._score(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_scorer.py", line 344, in _score
    response_method = _check_response_method(estimator, self._response_method)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 2106, in _check_response_method
    raise AttributeError(
AttributeError: Pipeline has none of the following attributes: predict_proba.

  warnings.warn(

2024-03-18 20:17:31,091:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py:196: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method='predict_proba', average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 188, in _score
    return super()._score(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_scorer.py", line 344, in _score
    response_method = _check_response_method(estimator, self._response_method)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 2106, in _check_response_method
    raise AttributeError(
AttributeError: Pipeline has none of the following attributes: predict_proba.

  warnings.warn(

2024-03-18 20:17:31,116:INFO:Calculating mean and std
2024-03-18 20:17:31,117:INFO:Creating metrics dataframe
2024-03-18 20:17:31,120:INFO:Uploading results into container
2024-03-18 20:17:31,121:INFO:Uploading model into container now
2024-03-18 20:17:31,122:INFO:_master_model_container: 6
2024-03-18 20:17:31,122:INFO:_display_container: 2
2024-03-18 20:17:31,122:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=7931, solver='auto',
                tol=0.0001)
2024-03-18 20:17:31,122:INFO:create_model() successfully completed......................................
2024-03-18 20:17:31,228:INFO:SubProcess create_model() end ==================================
2024-03-18 20:17:31,228:INFO:Creating metrics dataframe
2024-03-18 20:17:31,242:INFO:Initializing Random Forest Classifier
2024-03-18 20:17:31,242:INFO:Total runtime is 0.2786000529925029 minutes
2024-03-18 20:17:31,247:INFO:SubProcess create_model() called ==================================
2024-03-18 20:17:31,248:INFO:Initializing create_model()
2024-03-18 20:17:31,248:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000017B2EE0B8E0>, estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000017B4DA55000>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-03-18 20:17:31,248:INFO:Checking exceptions
2024-03-18 20:17:31,248:INFO:Importing libraries
2024-03-18 20:17:31,248:INFO:Copying training dataset
2024-03-18 20:17:31,253:INFO:Defining folds
2024-03-18 20:17:31,254:INFO:Declaring metric variables
2024-03-18 20:17:31,259:INFO:Importing untrained model
2024-03-18 20:17:31,264:INFO:Random Forest Classifier Imported successfully
2024-03-18 20:17:31,272:INFO:Starting cross validation
2024-03-18 20:17:31,273:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2024-03-18 20:17:31,874:INFO:Calculating mean and std
2024-03-18 20:17:31,875:INFO:Creating metrics dataframe
2024-03-18 20:17:31,880:INFO:Uploading results into container
2024-03-18 20:17:31,881:INFO:Uploading model into container now
2024-03-18 20:17:31,882:INFO:_master_model_container: 7
2024-03-18 20:17:31,882:INFO:_display_container: 2
2024-03-18 20:17:31,883:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       monotonic_cst=None, n_estimators=100, n_jobs=-1,
                       oob_score=False, random_state=7931, verbose=0,
                       warm_start=False)
2024-03-18 20:17:31,883:INFO:create_model() successfully completed......................................
2024-03-18 20:17:32,009:INFO:SubProcess create_model() end ==================================
2024-03-18 20:17:32,009:INFO:Creating metrics dataframe
2024-03-18 20:17:32,029:INFO:Initializing Quadratic Discriminant Analysis
2024-03-18 20:17:32,029:INFO:Total runtime is 0.29170800447463996 minutes
2024-03-18 20:17:32,036:INFO:SubProcess create_model() called ==================================
2024-03-18 20:17:32,037:INFO:Initializing create_model()
2024-03-18 20:17:32,038:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000017B2EE0B8E0>, estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000017B4DA55000>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-03-18 20:17:32,038:INFO:Checking exceptions
2024-03-18 20:17:32,038:INFO:Importing libraries
2024-03-18 20:17:32,038:INFO:Copying training dataset
2024-03-18 20:17:32,044:INFO:Defining folds
2024-03-18 20:17:32,044:INFO:Declaring metric variables
2024-03-18 20:17:32,050:INFO:Importing untrained model
2024-03-18 20:17:32,055:INFO:Quadratic Discriminant Analysis Imported successfully
2024-03-18 20:17:32,064:INFO:Starting cross validation
2024-03-18 20:17:32,065:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2024-03-18 20:17:32,099:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2024-03-18 20:17:32,099:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2024-03-18 20:17:32,100:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2024-03-18 20:17:32,101:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2024-03-18 20:17:32,104:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2024-03-18 20:17:32,107:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2024-03-18 20:17:32,109:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2024-03-18 20:17:32,110:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: divide by zero encountered in power
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,110:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: invalid value encountered in multiply
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,110:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: divide by zero encountered in power
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,110:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: divide by zero encountered in power
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,111:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: invalid value encountered in multiply
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,111:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: invalid value encountered in multiply
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,111:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: divide by zero encountered in power
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,112:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: invalid value encountered in multiply
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,112:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: divide by zero encountered in power
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,112:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: invalid value encountered in multiply
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,112:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2024-03-18 20:17:32,112:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:963: RuntimeWarning: divide by zero encountered in log
  u = np.asarray([np.sum(np.log(s)) for s in self.scalings_])

2024-03-18 20:17:32,112:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:963: RuntimeWarning: divide by zero encountered in log
  u = np.asarray([np.sum(np.log(s)) for s in self.scalings_])

2024-03-18 20:17:32,112:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:963: RuntimeWarning: divide by zero encountered in log
  u = np.asarray([np.sum(np.log(s)) for s in self.scalings_])

2024-03-18 20:17:32,112:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:963: RuntimeWarning: divide by zero encountered in log
  u = np.asarray([np.sum(np.log(s)) for s in self.scalings_])

2024-03-18 20:17:32,114:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2024-03-18 20:17:32,116:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: divide by zero encountered in power
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,116:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: invalid value encountered in multiply
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,116:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:963: RuntimeWarning: divide by zero encountered in log
  u = np.asarray([np.sum(np.log(s)) for s in self.scalings_])

2024-03-18 20:17:32,116:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: divide by zero encountered in power
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,117:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: invalid value encountered in multiply
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,117:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:963: RuntimeWarning: divide by zero encountered in log
  u = np.asarray([np.sum(np.log(s)) for s in self.scalings_])

2024-03-18 20:17:32,120:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: divide by zero encountered in power
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,120:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: invalid value encountered in multiply
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,121:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:963: RuntimeWarning: divide by zero encountered in log
  u = np.asarray([np.sum(np.log(s)) for s in self.scalings_])

2024-03-18 20:17:32,122:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: divide by zero encountered in power
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,122:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: invalid value encountered in multiply
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,123:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:963: RuntimeWarning: divide by zero encountered in log
  u = np.asarray([np.sum(np.log(s)) for s in self.scalings_])

2024-03-18 20:17:32,123:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: divide by zero encountered in power
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,123:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: divide by zero encountered in power
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,123:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: invalid value encountered in multiply
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,123:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: invalid value encountered in multiply
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,123:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:963: RuntimeWarning: divide by zero encountered in log
  u = np.asarray([np.sum(np.log(s)) for s in self.scalings_])

2024-03-18 20:17:32,124:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: divide by zero encountered in power
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,124:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:963: RuntimeWarning: divide by zero encountered in log
  u = np.asarray([np.sum(np.log(s)) for s in self.scalings_])

2024-03-18 20:17:32,124:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: invalid value encountered in multiply
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,124:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: divide by zero encountered in power
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,124:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:963: RuntimeWarning: divide by zero encountered in log
  u = np.asarray([np.sum(np.log(s)) for s in self.scalings_])

2024-03-18 20:17:32,124:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: invalid value encountered in multiply
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,124:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: divide by zero encountered in power
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,124:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: invalid value encountered in multiply
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,124:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:963: RuntimeWarning: divide by zero encountered in log
  u = np.asarray([np.sum(np.log(s)) for s in self.scalings_])

2024-03-18 20:17:32,124:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:963: RuntimeWarning: divide by zero encountered in log
  u = np.asarray([np.sum(np.log(s)) for s in self.scalings_])

2024-03-18 20:17:32,125:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: divide by zero encountered in power
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,125:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: invalid value encountered in multiply
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,126:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:963: RuntimeWarning: divide by zero encountered in log
  u = np.asarray([np.sum(np.log(s)) for s in self.scalings_])

2024-03-18 20:17:32,127:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: divide by zero encountered in power
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,127:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: invalid value encountered in multiply
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,127:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:963: RuntimeWarning: divide by zero encountered in log
  u = np.asarray([np.sum(np.log(s)) for s in self.scalings_])

2024-03-18 20:17:32,128:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: divide by zero encountered in power
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,128:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: invalid value encountered in multiply
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,128:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:963: RuntimeWarning: divide by zero encountered in log
  u = np.asarray([np.sum(np.log(s)) for s in self.scalings_])

2024-03-18 20:17:32,131:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py:196: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method='predict_proba', average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 188, in _score
    return super()._score(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_scorer.py", line 350, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 136, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_ranking.py", line 619, in roc_auc_score
    y_score = check_array(y_score, ensure_2d=False)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 1049, in check_array
    _assert_all_finite(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 126, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 175, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input contains NaN.

  warnings.warn(

2024-03-18 20:17:32,131:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py:196: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method='predict_proba', average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 188, in _score
    return super()._score(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_scorer.py", line 350, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 136, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_ranking.py", line 619, in roc_auc_score
    y_score = check_array(y_score, ensure_2d=False)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 1049, in check_array
    _assert_all_finite(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 126, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 175, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input contains NaN.

  warnings.warn(

2024-03-18 20:17:32,132:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: divide by zero encountered in power
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,132:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: invalid value encountered in multiply
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,132:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py:196: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method='predict_proba', average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 188, in _score
    return super()._score(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_scorer.py", line 350, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 136, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_ranking.py", line 619, in roc_auc_score
    y_score = check_array(y_score, ensure_2d=False)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 1049, in check_array
    _assert_all_finite(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 126, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 175, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input contains NaN.

  warnings.warn(

2024-03-18 20:17:32,132:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:963: RuntimeWarning: divide by zero encountered in log
  u = np.asarray([np.sum(np.log(s)) for s in self.scalings_])

2024-03-18 20:17:32,133:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py:196: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method='predict_proba', average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 188, in _score
    return super()._score(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_scorer.py", line 350, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 136, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_ranking.py", line 619, in roc_auc_score
    y_score = check_array(y_score, ensure_2d=False)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 1049, in check_array
    _assert_all_finite(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 126, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 175, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input contains NaN.

  warnings.warn(

2024-03-18 20:17:32,133:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py:196: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method='predict_proba', average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 188, in _score
    return super()._score(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_scorer.py", line 350, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 136, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_ranking.py", line 619, in roc_auc_score
    y_score = check_array(y_score, ensure_2d=False)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 1049, in check_array
    _assert_all_finite(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 126, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 175, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input contains NaN.

  warnings.warn(

2024-03-18 20:17:32,134:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: divide by zero encountered in power
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,134:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: invalid value encountered in multiply
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,135:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:963: RuntimeWarning: divide by zero encountered in log
  u = np.asarray([np.sum(np.log(s)) for s in self.scalings_])

2024-03-18 20:17:32,135:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py:196: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method='predict_proba', average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 188, in _score
    return super()._score(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_scorer.py", line 350, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 136, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_ranking.py", line 619, in roc_auc_score
    y_score = check_array(y_score, ensure_2d=False)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 1049, in check_array
    _assert_all_finite(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 126, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 175, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input contains NaN.

  warnings.warn(

2024-03-18 20:17:32,135:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: divide by zero encountered in power
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,135:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:960: RuntimeWarning: invalid value encountered in multiply
  X2 = np.dot(Xm, R * (S ** (-0.5)))

2024-03-18 20:17:32,135:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\discriminant_analysis.py:963: RuntimeWarning: divide by zero encountered in log
  u = np.asarray([np.sum(np.log(s)) for s in self.scalings_])

2024-03-18 20:17:32,139:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py:196: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method='predict_proba', average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 188, in _score
    return super()._score(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_scorer.py", line 350, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 136, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_ranking.py", line 619, in roc_auc_score
    y_score = check_array(y_score, ensure_2d=False)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 1049, in check_array
    _assert_all_finite(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 126, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 175, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input contains NaN.

  warnings.warn(

2024-03-18 20:17:32,141:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py:196: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method='predict_proba', average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 188, in _score
    return super()._score(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_scorer.py", line 350, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 136, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_ranking.py", line 619, in roc_auc_score
    y_score = check_array(y_score, ensure_2d=False)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 1049, in check_array
    _assert_all_finite(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 126, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 175, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input contains NaN.

  warnings.warn(

2024-03-18 20:17:32,141:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py:196: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method='predict_proba', average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 188, in _score
    return super()._score(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_scorer.py", line 350, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\metrics.py", line 136, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_ranking.py", line 619, in roc_auc_score
    y_score = check_array(y_score, ensure_2d=False)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 1049, in check_array
    _assert_all_finite(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 126, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\utils\validation.py", line 175, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input contains NaN.

  warnings.warn(

2024-03-18 20:17:32,142:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2024-03-18 20:17:32,142:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2024-03-18 20:17:32,144:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2024-03-18 20:17:32,144:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2024-03-18 20:17:32,146:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2024-03-18 20:17:32,146:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2024-03-18 20:17:32,148:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2024-03-18 20:17:32,150:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2024-03-18 20:17:32,154:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2024-03-18 20:17:32,155:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2024-03-18 20:17:32,164:INFO:Calculating mean and std
2024-03-18 20:17:32,165:INFO:Creating metrics dataframe
2024-03-18 20:17:32,169:INFO:Uploading results into container
2024-03-18 20:17:32,169:INFO:Uploading model into container now
2024-03-18 20:17:32,170:INFO:_master_model_container: 8
2024-03-18 20:17:32,170:INFO:_display_container: 2
2024-03-18 20:17:32,170:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2024-03-18 20:17:32,170:INFO:create_model() successfully completed......................................
2024-03-18 20:17:32,309:INFO:SubProcess create_model() end ==================================
2024-03-18 20:17:32,309:INFO:Creating metrics dataframe
2024-03-18 20:17:32,324:INFO:Initializing Ada Boost Classifier
2024-03-18 20:17:32,324:INFO:Total runtime is 0.29662454922993986 minutes
2024-03-18 20:17:32,329:INFO:SubProcess create_model() called ==================================
2024-03-18 20:17:32,330:INFO:Initializing create_model()
2024-03-18 20:17:32,330:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000017B2EE0B8E0>, estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000017B4DA55000>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-03-18 20:17:32,330:INFO:Checking exceptions
2024-03-18 20:17:32,330:INFO:Importing libraries
2024-03-18 20:17:32,330:INFO:Copying training dataset
2024-03-18 20:17:32,335:INFO:Defining folds
2024-03-18 20:17:32,335:INFO:Declaring metric variables
2024-03-18 20:17:32,341:INFO:Importing untrained model
2024-03-18 20:17:32,347:INFO:Ada Boost Classifier Imported successfully
2024-03-18 20:17:32,356:INFO:Starting cross validation
2024-03-18 20:17:32,358:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2024-03-18 20:17:32,385:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

2024-03-18 20:17:32,386:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

2024-03-18 20:17:32,390:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

2024-03-18 20:17:32,391:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

2024-03-18 20:17:32,396:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

2024-03-18 20:17:32,401:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

2024-03-18 20:17:32,402:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

2024-03-18 20:17:32,404:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

2024-03-18 20:17:32,406:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

2024-03-18 20:17:32,413:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

2024-03-18 20:17:32,683:INFO:Calculating mean and std
2024-03-18 20:17:32,684:INFO:Creating metrics dataframe
2024-03-18 20:17:32,688:INFO:Uploading results into container
2024-03-18 20:17:32,688:INFO:Uploading model into container now
2024-03-18 20:17:32,689:INFO:_master_model_container: 9
2024-03-18 20:17:32,689:INFO:_display_container: 2
2024-03-18 20:17:32,689:INFO:AdaBoostClassifier(algorithm='SAMME.R', estimator=None, learning_rate=1.0,
                   n_estimators=50, random_state=7931)
2024-03-18 20:17:32,689:INFO:create_model() successfully completed......................................
2024-03-18 20:17:32,800:INFO:SubProcess create_model() end ==================================
2024-03-18 20:17:32,801:INFO:Creating metrics dataframe
2024-03-18 20:17:32,814:INFO:Initializing Gradient Boosting Classifier
2024-03-18 20:17:32,815:INFO:Total runtime is 0.3048136313756308 minutes
2024-03-18 20:17:32,819:INFO:SubProcess create_model() called ==================================
2024-03-18 20:17:32,820:INFO:Initializing create_model()
2024-03-18 20:17:32,820:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000017B2EE0B8E0>, estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000017B4DA55000>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-03-18 20:17:32,821:INFO:Checking exceptions
2024-03-18 20:17:32,821:INFO:Importing libraries
2024-03-18 20:17:32,821:INFO:Copying training dataset
2024-03-18 20:17:32,825:INFO:Defining folds
2024-03-18 20:17:32,825:INFO:Declaring metric variables
2024-03-18 20:17:32,830:INFO:Importing untrained model
2024-03-18 20:17:32,835:INFO:Gradient Boosting Classifier Imported successfully
2024-03-18 20:17:32,843:INFO:Starting cross validation
2024-03-18 20:17:32,845:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2024-03-18 20:17:33,219:INFO:Calculating mean and std
2024-03-18 20:17:33,220:INFO:Creating metrics dataframe
2024-03-18 20:17:33,224:INFO:Uploading results into container
2024-03-18 20:17:33,225:INFO:Uploading model into container now
2024-03-18 20:17:33,226:INFO:_master_model_container: 10
2024-03-18 20:17:33,226:INFO:_display_container: 2
2024-03-18 20:17:33,227:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=7931, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2024-03-18 20:17:33,227:INFO:create_model() successfully completed......................................
2024-03-18 20:17:33,334:INFO:SubProcess create_model() end ==================================
2024-03-18 20:17:33,334:INFO:Creating metrics dataframe
2024-03-18 20:17:33,350:INFO:Initializing Linear Discriminant Analysis
2024-03-18 20:17:33,350:INFO:Total runtime is 0.31373193264007576 minutes
2024-03-18 20:17:33,356:INFO:SubProcess create_model() called ==================================
2024-03-18 20:17:33,356:INFO:Initializing create_model()
2024-03-18 20:17:33,356:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000017B2EE0B8E0>, estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000017B4DA55000>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-03-18 20:17:33,357:INFO:Checking exceptions
2024-03-18 20:17:33,357:INFO:Importing libraries
2024-03-18 20:17:33,357:INFO:Copying training dataset
2024-03-18 20:17:33,363:INFO:Defining folds
2024-03-18 20:17:33,364:INFO:Declaring metric variables
2024-03-18 20:17:33,370:INFO:Importing untrained model
2024-03-18 20:17:33,376:INFO:Linear Discriminant Analysis Imported successfully
2024-03-18 20:17:33,387:INFO:Starting cross validation
2024-03-18 20:17:33,388:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2024-03-18 20:17:33,538:INFO:Calculating mean and std
2024-03-18 20:17:33,539:INFO:Creating metrics dataframe
2024-03-18 20:17:33,543:INFO:Uploading results into container
2024-03-18 20:17:33,544:INFO:Uploading model into container now
2024-03-18 20:17:33,544:INFO:_master_model_container: 11
2024-03-18 20:17:33,545:INFO:_display_container: 2
2024-03-18 20:17:33,545:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2024-03-18 20:17:33,546:INFO:create_model() successfully completed......................................
2024-03-18 20:17:33,635:INFO:SubProcess create_model() end ==================================
2024-03-18 20:17:33,635:INFO:Creating metrics dataframe
2024-03-18 20:17:33,648:INFO:Initializing Extra Trees Classifier
2024-03-18 20:17:33,648:INFO:Total runtime is 0.31869482994079595 minutes
2024-03-18 20:17:33,652:INFO:SubProcess create_model() called ==================================
2024-03-18 20:17:33,652:INFO:Initializing create_model()
2024-03-18 20:17:33,652:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000017B2EE0B8E0>, estimator=et, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000017B4DA55000>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-03-18 20:17:33,652:INFO:Checking exceptions
2024-03-18 20:17:33,652:INFO:Importing libraries
2024-03-18 20:17:33,652:INFO:Copying training dataset
2024-03-18 20:17:33,657:INFO:Defining folds
2024-03-18 20:17:33,657:INFO:Declaring metric variables
2024-03-18 20:17:33,662:INFO:Importing untrained model
2024-03-18 20:17:33,666:INFO:Extra Trees Classifier Imported successfully
2024-03-18 20:17:33,675:INFO:Starting cross validation
2024-03-18 20:17:33,676:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2024-03-18 20:17:34,164:INFO:Calculating mean and std
2024-03-18 20:17:34,165:INFO:Creating metrics dataframe
2024-03-18 20:17:34,169:INFO:Uploading results into container
2024-03-18 20:17:34,170:INFO:Uploading model into container now
2024-03-18 20:17:34,170:INFO:_master_model_container: 12
2024-03-18 20:17:34,170:INFO:_display_container: 2
2024-03-18 20:17:34,171:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     monotonic_cst=None, n_estimators=100, n_jobs=-1,
                     oob_score=False, random_state=7931, verbose=0,
                     warm_start=False)
2024-03-18 20:17:34,171:INFO:create_model() successfully completed......................................
2024-03-18 20:17:34,279:INFO:SubProcess create_model() end ==================================
2024-03-18 20:17:34,279:INFO:Creating metrics dataframe
2024-03-18 20:17:34,295:INFO:Initializing Extreme Gradient Boosting
2024-03-18 20:17:34,295:INFO:Total runtime is 0.3294836680094402 minutes
2024-03-18 20:17:34,300:INFO:SubProcess create_model() called ==================================
2024-03-18 20:17:34,666:INFO:Initializing create_model()
2024-03-18 20:17:34,666:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000017B2EE0B8E0>, estimator=xgboost, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000017B4DA55000>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-03-18 20:17:34,666:INFO:Checking exceptions
2024-03-18 20:17:34,667:INFO:Importing libraries
2024-03-18 20:17:34,667:INFO:Copying training dataset
2024-03-18 20:17:34,670:INFO:Defining folds
2024-03-18 20:17:34,670:INFO:Declaring metric variables
2024-03-18 20:17:34,675:INFO:Importing untrained model
2024-03-18 20:17:34,680:INFO:Extreme Gradient Boosting Imported successfully
2024-03-18 20:17:34,688:INFO:Starting cross validation
2024-03-18 20:17:34,690:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2024-03-18 20:17:36,876:INFO:Calculating mean and std
2024-03-18 20:17:36,877:INFO:Creating metrics dataframe
2024-03-18 20:17:36,881:INFO:Uploading results into container
2024-03-18 20:17:36,882:INFO:Uploading model into container now
2024-03-18 20:17:36,882:INFO:_master_model_container: 13
2024-03-18 20:17:36,883:INFO:_display_container: 2
2024-03-18 20:17:36,884:INFO:XGBClassifier(base_score=None, booster='gbtree', callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, gamma=None,
              gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, n_estimators=100, n_jobs=-1,
              num_parallel_tree=None, objective='binary:logistic',
              predictor=None, random_state=7931, reg_alpha=None, ...)
2024-03-18 20:17:36,884:INFO:create_model() successfully completed......................................
2024-03-18 20:17:36,987:INFO:SubProcess create_model() end ==================================
2024-03-18 20:17:36,987:INFO:Creating metrics dataframe
2024-03-18 20:17:37,002:INFO:Initializing Light Gradient Boosting Machine
2024-03-18 20:17:37,002:INFO:Total runtime is 0.3745973388353984 minutes
2024-03-18 20:17:37,006:INFO:SubProcess create_model() called ==================================
2024-03-18 20:17:37,007:INFO:Initializing create_model()
2024-03-18 20:17:37,007:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000017B2EE0B8E0>, estimator=lightgbm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000017B4DA55000>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-03-18 20:17:37,008:INFO:Checking exceptions
2024-03-18 20:17:37,008:INFO:Importing libraries
2024-03-18 20:17:37,008:INFO:Copying training dataset
2024-03-18 20:17:37,013:INFO:Defining folds
2024-03-18 20:17:37,014:INFO:Declaring metric variables
2024-03-18 20:17:37,020:INFO:Importing untrained model
2024-03-18 20:17:37,026:INFO:Light Gradient Boosting Machine Imported successfully
2024-03-18 20:17:37,037:INFO:Starting cross validation
2024-03-18 20:17:37,039:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2024-03-18 20:17:38,674:INFO:Calculating mean and std
2024-03-18 20:17:38,676:INFO:Creating metrics dataframe
2024-03-18 20:17:38,682:INFO:Uploading results into container
2024-03-18 20:17:38,683:INFO:Uploading model into container now
2024-03-18 20:17:38,684:INFO:_master_model_container: 14
2024-03-18 20:17:38,684:INFO:_display_container: 2
2024-03-18 20:17:38,685:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=7931, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)
2024-03-18 20:17:38,685:INFO:create_model() successfully completed......................................
2024-03-18 20:17:38,794:INFO:SubProcess create_model() end ==================================
2024-03-18 20:17:38,794:INFO:Creating metrics dataframe
2024-03-18 20:17:38,810:INFO:Initializing CatBoost Classifier
2024-03-18 20:17:38,810:INFO:Total runtime is 0.4047311703364055 minutes
2024-03-18 20:17:38,815:INFO:SubProcess create_model() called ==================================
2024-03-18 20:17:38,816:INFO:Initializing create_model()
2024-03-18 20:17:38,816:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000017B2EE0B8E0>, estimator=catboost, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000017B4DA55000>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-03-18 20:17:38,816:INFO:Checking exceptions
2024-03-18 20:17:38,816:INFO:Importing libraries
2024-03-18 20:17:38,816:INFO:Copying training dataset
2024-03-18 20:17:38,821:INFO:Defining folds
2024-03-18 20:17:38,822:INFO:Declaring metric variables
2024-03-18 20:17:38,827:INFO:Importing untrained model
2024-03-18 20:17:38,832:INFO:CatBoost Classifier Imported successfully
2024-03-18 20:17:38,843:INFO:Starting cross validation
2024-03-18 20:17:38,844:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2024-03-18 20:17:44,182:WARNING:c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\model_selection\_validation.py:547: FitFailedWarning: 
6 fits failed out of a total of 10.
The score on these train-test partitions for these parameters will be set to 0.0.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
6 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\pipeline.py", line 276, in fit
    fitted_estimator = self._memory_fit(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\joblib\memory.py", line 349, in __call__
    return self.func(*args, **kwargs)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\pycaret\internal\pipeline.py", line 69, in _fit_one
    transformer.fit(*args)
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\catboost\core.py", line 5128, in fit
    self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\catboost\core.py", line 2355, in _fit
    self._train(
  File "c:\Users\YK\anaconda3\envs\pyt\lib\site-packages\catboost\core.py", line 1759, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 4623, in _catboost._CatBoost._train
  File "_catboost.pyx", line 4672, in _catboost._CatBoost._train
_catboost.CatBoostError: C:/Program Files (x86)/Go Agent/pipelines/BuildMaster/catboost.git/catboost/libs/train_lib/dir_helper.cpp:20: Can't create train working dir: catboost_info

  warnings.warn(some_fits_failed_message, FitFailedWarning)

2024-03-18 20:17:44,183:INFO:Calculating mean and std
2024-03-18 20:17:44,184:INFO:Creating metrics dataframe
2024-03-18 20:17:44,188:INFO:Uploading results into container
2024-03-18 20:17:44,188:INFO:Uploading model into container now
2024-03-18 20:17:44,189:INFO:_master_model_container: 15
2024-03-18 20:17:44,189:INFO:_display_container: 2
2024-03-18 20:17:44,190:INFO:<catboost.core.CatBoostClassifier object at 0x0000017B4CE31AE0>
2024-03-18 20:17:44,190:INFO:create_model() successfully completed......................................
2024-03-18 20:17:44,303:INFO:SubProcess create_model() end ==================================
2024-03-18 20:17:44,303:INFO:Creating metrics dataframe
2024-03-18 20:17:44,319:INFO:Initializing Dummy Classifier
2024-03-18 20:17:44,319:INFO:Total runtime is 0.496537721157074 minutes
2024-03-18 20:17:44,323:INFO:SubProcess create_model() called ==================================
2024-03-18 20:17:44,324:INFO:Initializing create_model()
2024-03-18 20:17:44,325:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000017B2EE0B8E0>, estimator=dummy, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000017B4DA55000>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-03-18 20:17:44,325:INFO:Checking exceptions
2024-03-18 20:17:44,325:INFO:Importing libraries
2024-03-18 20:17:44,325:INFO:Copying training dataset
2024-03-18 20:17:44,331:INFO:Defining folds
2024-03-18 20:17:44,332:INFO:Declaring metric variables
2024-03-18 20:17:44,338:INFO:Importing untrained model
2024-03-18 20:17:44,343:INFO:Dummy Classifier Imported successfully
2024-03-18 20:17:44,357:INFO:Starting cross validation
2024-03-18 20:17:44,358:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2024-03-18 20:17:44,465:INFO:Calculating mean and std
2024-03-18 20:17:44,466:INFO:Creating metrics dataframe
2024-03-18 20:17:44,469:INFO:Uploading results into container
2024-03-18 20:17:44,470:INFO:Uploading model into container now
2024-03-18 20:17:44,471:INFO:_master_model_container: 16
2024-03-18 20:17:44,471:INFO:_display_container: 2
2024-03-18 20:17:44,472:INFO:DummyClassifier(constant=None, random_state=7931, strategy='prior')
2024-03-18 20:17:44,473:INFO:create_model() successfully completed......................................
2024-03-18 20:17:44,577:INFO:SubProcess create_model() end ==================================
2024-03-18 20:17:44,577:INFO:Creating metrics dataframe
2024-03-18 20:17:44,606:INFO:Initializing create_model()
2024-03-18 20:17:44,606:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000017B2EE0B8E0>, estimator=ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     monotonic_cst=None, n_estimators=100, n_jobs=-1,
                     oob_score=False, random_state=7931, verbose=0,
                     warm_start=False), fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-03-18 20:17:44,607:INFO:Checking exceptions
2024-03-18 20:17:44,609:INFO:Importing libraries
2024-03-18 20:17:44,609:INFO:Copying training dataset
2024-03-18 20:17:44,612:INFO:Defining folds
2024-03-18 20:17:44,613:INFO:Declaring metric variables
2024-03-18 20:17:44,613:INFO:Importing untrained model
2024-03-18 20:17:44,613:INFO:Declaring custom model
2024-03-18 20:17:44,614:INFO:Extra Trees Classifier Imported successfully
2024-03-18 20:17:44,615:INFO:Cross validation set to False
2024-03-18 20:17:44,615:INFO:Fitting Model
2024-03-18 20:17:44,745:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     monotonic_cst=None, n_estimators=100, n_jobs=-1,
                     oob_score=False, random_state=7931, verbose=0,
                     warm_start=False)
2024-03-18 20:17:44,745:INFO:create_model() successfully completed......................................
2024-03-18 20:17:44,909:INFO:_master_model_container: 16
2024-03-18 20:17:44,909:INFO:_display_container: 2
2024-03-18 20:17:44,910:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     monotonic_cst=None, n_estimators=100, n_jobs=-1,
                     oob_score=False, random_state=7931, verbose=0,
                     warm_start=False)
2024-03-18 20:17:44,910:INFO:compare_models() successfully completed......................................
